# Generated by Django 4.1 on 2024-07-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0004_teachingmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingmaterial",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
