# Generated by Django 4.1 on 2024-08-05 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_remove_user_followers_num_remove_user_follows_num_and_more"),
        ("forum", "0005_teachingmaterial_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="pdfs/course_resources/", verbose_name="pdf_file"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="publish_date"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
