# Generated by Django 4.1 on 2024-08-05 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0006_courseresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "log_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Log Date"
                    ),
                ),
            ],
        ),
    ]
